// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/protocol/proto/envelope.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_UNKNOWN         MessageType = 0
	MessageType_HELLO           MessageType = 1
	MessageType_HELLO_ACK       MessageType = 2
	MessageType_PING            MessageType = 3
	MessageType_PONG            MessageType = 4
	MessageType_PEER_LIST       MessageType = 5
	MessageType_CHAT            MessageType = 6
	MessageType_SEARCH_REQUEST  MessageType = 7
	MessageType_SEARCH_RESPONSE MessageType = 8
	MessageType_FILE_ANNOUNCE   MessageType = 9
	MessageType_FILE_REQUEST    MessageType = 10
	MessageType_FILE_CHUNK      MessageType = 11
	MessageType_FILE_COMPLETE   MessageType = 12
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "HELLO",
		2:  "HELLO_ACK",
		3:  "PING",
		4:  "PONG",
		5:  "PEER_LIST",
		6:  "CHAT",
		7:  "SEARCH_REQUEST",
		8:  "SEARCH_RESPONSE",
		9:  "FILE_ANNOUNCE",
		10: "FILE_REQUEST",
		11: "FILE_CHUNK",
		12: "FILE_COMPLETE",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":         0,
		"HELLO":           1,
		"HELLO_ACK":       2,
		"PING":            3,
		"PONG":            4,
		"PEER_LIST":       5,
		"CHAT":            6,
		"SEARCH_REQUEST":  7,
		"SEARCH_RESPONSE": 8,
		"FILE_ANNOUNCE":   9,
		"FILE_REQUEST":    10,
		"FILE_CHUNK":      11,
		"FILE_COMPLETE":   12,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_proto_envelope_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_internal_protocol_proto_envelope_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_proto_envelope_proto_rawDescGZIP(), []int{0}
}

type Envelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderPeerId    string                 `protobuf:"bytes,2,opt,name=sender_peer_id,json=senderPeerId,proto3" json:"sender_peer_id,omitempty"`
	TimestampMs     int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Type            MessageType            `protobuf:"varint,4,opt,name=type,proto3,enum=nexus.protocol.MessageType" json:"type,omitempty"`
	ProtocolVersion uint32                 `protobuf:"varint,5,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Payload         []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature       []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_internal_protocol_proto_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Envelope) GetSenderPeerId() string {
	if x != nil {
		return x.SenderPeerId
	}
	return ""
}

func (x *Envelope) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Envelope) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

func (x *Envelope) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_internal_protocol_proto_envelope_proto protoreflect.FileDescriptor

const file_internal_protocol_proto_envelope_proto_rawDesc = "" +
	"\n" +
	"&internal/protocol/proto/envelope.proto\x12\x0enexus.protocol\"\x86\x02\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12$\n" +
	"\x0esender_peer_id\x18\x02 \x01(\tR\fsenderPeerId\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12/\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1b.nexus.protocol.MessageTypeR\x04type\x12)\n" +
	"\x10protocol_version\x18\x05 \x01(\rR\x0fprotocolVersion\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature*\xd2\x01\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05HELLO\x10\x01\x12\r\n" +
	"\tHELLO_ACK\x10\x02\x12\b\n" +
	"\x04PING\x10\x03\x12\b\n" +
	"\x04PONG\x10\x04\x12\r\n" +
	"\tPEER_LIST\x10\x05\x12\b\n" +
	"\x04CHAT\x10\x06\x12\x12\n" +
	"\x0eSEARCH_REQUEST\x10\a\x12\x13\n" +
	"\x0fSEARCH_RESPONSE\x10\b\x12\x11\n" +
	"\rFILE_ANNOUNCE\x10\t\x12\x10\n" +
	"\fFILE_REQUEST\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"FILE_CHUNK\x10\v\x12\x11\n" +
	"\rFILE_COMPLETE\x10\fB3Z1github.com/awatansh/nexus/internal/protocol/protob\x06proto3"

var (
	file_internal_protocol_proto_envelope_proto_rawDescOnce sync.Once
	file_internal_protocol_proto_envelope_proto_rawDescData []byte
)

func file_internal_protocol_proto_envelope_proto_rawDescGZIP() []byte {
	file_internal_protocol_proto_envelope_proto_rawDescOnce.Do(func() {
		file_internal_protocol_proto_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_proto_envelope_proto_rawDesc), len(file_internal_protocol_proto_envelope_proto_rawDesc)))
	})
	return file_internal_protocol_proto_envelope_proto_rawDescData
}

var file_internal_protocol_proto_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_protocol_proto_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_protocol_proto_envelope_proto_goTypes = []any{
	(MessageType)(0), // 0: nexus.protocol.MessageType
	(*Envelope)(nil), // 1: nexus.protocol.Envelope
}
var file_internal_protocol_proto_envelope_proto_depIdxs = []int32{
	0, // 0: nexus.protocol.Envelope.type:type_name -> nexus.protocol.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_protocol_proto_envelope_proto_init() }
func file_internal_protocol_proto_envelope_proto_init() {
	if File_internal_protocol_proto_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_proto_envelope_proto_rawDesc), len(file_internal_protocol_proto_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_proto_envelope_proto_goTypes,
		DependencyIndexes: file_internal_protocol_proto_envelope_proto_depIdxs,
		EnumInfos:         file_internal_protocol_proto_envelope_proto_enumTypes,
		MessageInfos:      file_internal_protocol_proto_envelope_proto_msgTypes,
	}.Build()
	File_internal_protocol_proto_envelope_proto = out.File
	file_internal_protocol_proto_envelope_proto_goTypes = nil
	file_internal_protocol_proto_envelope_proto_depIdxs = nil
}
