// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/protocol/proto/ping.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_internal_protocol_proto_ping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_ping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_ping_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_internal_protocol_proto_ping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_ping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_ping_proto_rawDescGZIP(), []int{1}
}

func (x *Pong) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

var File_internal_protocol_proto_ping_proto protoreflect.FileDescriptor

const file_internal_protocol_proto_ping_proto_rawDesc = "" +
	"\n" +
	"\"internal/protocol/proto/ping.proto\x12\x0enexus.protocol\")\n" +
	"\x04Ping\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\")\n" +
	"\x04Pong\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMsB3Z1github.com/awatansh/nexus/internal/protocol/protob\x06proto3"

var (
	file_internal_protocol_proto_ping_proto_rawDescOnce sync.Once
	file_internal_protocol_proto_ping_proto_rawDescData []byte
)

func file_internal_protocol_proto_ping_proto_rawDescGZIP() []byte {
	file_internal_protocol_proto_ping_proto_rawDescOnce.Do(func() {
		file_internal_protocol_proto_ping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_proto_ping_proto_rawDesc), len(file_internal_protocol_proto_ping_proto_rawDesc)))
	})
	return file_internal_protocol_proto_ping_proto_rawDescData
}

var file_internal_protocol_proto_ping_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_protocol_proto_ping_proto_goTypes = []any{
	(*Ping)(nil), // 0: nexus.protocol.Ping
	(*Pong)(nil), // 1: nexus.protocol.Pong
}
var file_internal_protocol_proto_ping_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protocol_proto_ping_proto_init() }
func file_internal_protocol_proto_ping_proto_init() {
	if File_internal_protocol_proto_ping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_proto_ping_proto_rawDesc), len(file_internal_protocol_proto_ping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_proto_ping_proto_goTypes,
		DependencyIndexes: file_internal_protocol_proto_ping_proto_depIdxs,
		MessageInfos:      file_internal_protocol_proto_ping_proto_msgTypes,
	}.Build()
	File_internal_protocol_proto_ping_proto = out.File
	file_internal_protocol_proto_ping_proto_goTypes = nil
	file_internal_protocol_proto_ping_proto_depIdxs = nil
}
